// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['App']['Add'](arg1, arg2);
}

export function ChooseOutput() {
  return window['go']['main']['App']['ChooseOutput']();
}

export function ChooseTorrent() {
  return window['go']['main']['App']['ChooseTorrent']();
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function ListTasks(arg1, arg2) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2);
}

export function OpenOutput() {
  return window['go']['main']['App']['OpenOutput']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SetOutput(arg1) {
  return window['go']['main']['App']['SetOutput'](arg1);
}
