// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {config} from '../models';

export function Add(arg1:string,arg2:string):Promise<engine.Task>;

export function ChooseOutput():Promise<string>;

export function ChooseTorrent():Promise<string>;

export function Config():Promise<config.PublicConfig>;

export function ListTasks(arg1:number,arg2:number):Promise<engine.TaskPage>;

export function OpenOutput():Promise<void>;

export function Pause(arg1:string):Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function Resume(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SetOutput(arg1:string):Promise<void>;
